name: Build/release

on:
  pull_request:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: ğŸ§° Install Dependencies
        run: npm install

      - name: ğŸ”¨ Build
        run: npm run make

      - name: â¬†ï¸ Upload Production Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ format('{0}-artifacts', matrix.os) }}
          path: out/make/**/**

  release:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v2

      - name: â¬ Download Artifacts
        uses: actions/download-artifact@v2

      - name: âœï¸ Generate release changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ†• Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            macos-latest-artifacts/**
            windows-latest-artifacts/**
            ubuntu-latest-artifacts/**
          body: ${{steps.changelog.outputs.changelog}}
