name: Build/release

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**/*.yml"
      - ".gitignore"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: ğŸ§° Install Dependencies
        run: npm install

      - name: ğŸ”¨ Build
        run: npm run make

      - name: â¬†ï¸ Upload Production Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ format('{0}-artifacts', matrix.os) }}
          path: out/make/**/**

  release:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v2

      - name: â¬ Download Artifacts
        uses: actions/download-artifact@v2

      - name: ğŸ·ï¸ Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-path: ./package.json

      - name: âœï¸ Generate release changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          stripGeneratorNotice: true

      - name: ğŸ“™ Generate changelog (Commits Only)
        id: changelogv2
        uses: jaywcjlove/changelog-generator@main
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: ğŸ†• Release
        uses: softprops/action-gh-release@v1
        if: steps.create_tag.outputs.successful
        with:
          files: |
            macos-latest-artifacts/**
            windows-latest-artifacts/**
            ubuntu-latest-artifacts/**
          body: |
            ${{steps.changelog.outputs.changelog}}
            #{{steps.changelogv2.outputs.changelog}}
          tag_name: ${{ steps.create_tag.outputs.version }}

      - name: ğŸ§¹ Cleanup
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            macos-latest-artifacts
            windows-latest-artifacts
            ubuntu-latest-artifacts
